INSERT INTO CURRENCY (ID, CURRENCY_CODE, CURRENCY_DESC) VALUES (1,'USD','US Dollar');
INSERT INTO CURRENCY (ID, CURRENCY_CODE, CURRENCY_DESC) VALUES (2,'EUR','Euro');
INSERT INTO CURRENCY (ID, CURRENCY_CODE, CURRENCY_DESC) VALUES (3,'GBP','British Pound');
INSERT INTO CURRENCY (ID, CURRENCY_CODE, CURRENCY_DESC) VALUES (4,'INR','Indian Rupee');
INSERT INTO CURRENCY (ID, CURRENCY_CODE, CURRENCY_DESC) VALUES (5,'AUD','Australian Dollar');
INSERT INTO CURRENCY (ID, CURRENCY_CODE, CURRENCY_DESC) VALUES (6,'CAD','Canadian Dollar');
INSERT INTO CURRENCY (ID, CURRENCY_CODE, CURRENCY_DESC) VALUES (7,'SGD','Singapore Dollar');
INSERT INTO CURRENCY (ID, CURRENCY_CODE, CURRENCY_DESC) VALUES (8,'CHF','Swiss Franc');
INSERT INTO CURRENCY (ID, CURRENCY_CODE, CURRENCY_DESC) VALUES (9,'MYR','Malaysian Ringgit');
INSERT INTO CURRENCY (ID, CURRENCY_CODE, CURRENCY_DESC) VALUES (10,'JPY','Japanese Yen');

INSERT INTO XCHANGE_RATE (ID, FROM_CURRENCY_CODE, TO_CURRENCY_CODE, RATE) VALUES ( 1, 1, 1, 1.0);
INSERT INTO XCHANGE_RATE (ID, FROM_CURRENCY_CODE, TO_CURRENCY_CODE, RATE) VALUES ( 2, 1, 2, 0.75);
INSERT INTO XCHANGE_RATE (ID, FROM_CURRENCY_CODE, TO_CURRENCY_CODE, RATE) VALUES ( 3, 1, 3, 0.5);
INSERT INTO XCHANGE_RATE (ID, FROM_CURRENCY_CODE, TO_CURRENCY_CODE, RATE) VALUES ( 4, 1, 4, 50.0);
INSERT INTO XCHANGE_RATE (ID, FROM_CURRENCY_CODE, TO_CURRENCY_CODE, RATE) VALUES ( 5, 1, 5, 1.5);
INSERT INTO XCHANGE_RATE (ID, FROM_CURRENCY_CODE, TO_CURRENCY_CODE, RATE) VALUES ( 6, 1, 6, 2.0);

--INSERT INTO XCHANGE_RATE VALUES ( 1, 1, 1, 1.0);
--INSERT INTO XCHANGE_RATE VALUES ( 2, 2, 1, 0.879241333);
--INSERT INTO XCHANGE_RATE VALUES ( 3, 3, 1, 0.780039674);
--INSERT INTO XCHANGE_RATE VALUES ( 4, 4, 1, 73.22916207);
--INSERT INTO XCHANGE_RATE VALUES ( 5, 5, 1, 1.412509071);
--INSERT INTO XCHANGE_RATE VALUES ( 6, 6, 1, 1.30740322);
--INSERT INTO XCHANGE_RATE VALUES ( 7, 7, 1, 1.380227214);
--INSERT INTO XCHANGE_RATE VALUES ( 8, 8, 1, 0.999473432);
--INSERT INTO XCHANGE_RATE VALUES ( 9, 9, 1, 4.168947376);
--INSERT INTO XCHANGE_RATE VALUES ( 10, 10, 1, 112.4137079);
